[package]
name = "octobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13"
serde = "1.0"
lazy_static = "1.4"
diesel_migrations = "2.0.0-rc.0"
tokio = { version = "1.19", features = ["full"] }
chrono = "0.4"
serde_json = "1.0.82"

[dependencies.serenity]
version = "0.11"

[dependencies.diesel]
version = "2.0.0-rc.0"
features = ["postgres", "r2d2", "chrono", "uuid"]

[dependencies.uuid]
version = "1.1.2"
features = ["v4", "serde"]
