[package]
name = "octobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13"
serde = "1.0"
lazy_static = "1.4"
diesel_migrations = "2.0.0"
tokio = { version = "1.19", features = ["full"] }
chrono = "0.4"
serde_json = "1.0.82"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["json", "env-filter"] }
tracing-appender = "0.2.2"
serenity = "0.11"
cron = "0.11.0"
parking_lot = "0.12.1"

[dependencies.diesel]
version = "2.0.0"
features = ["postgres", "r2d2", "chrono", "uuid"]

[dependencies.uuid]
version = "1.1.2"
features = ["v4", "serde"]
