[package]
name = "octobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13"
serde = "1.0"
lazy_static = "1.4"
diesel_migrations = "1.4"
tokio = { version = "1.19", features = ["full"] }
chrono = "0.4"
uuid = "0.8.2"

[dependencies.serenity]
version = "0.11"
features = ["framework", "standard_framework", "collector"]

[dependencies.diesel]
version = "1.4"
features = ["postgres", "r2d2", "uuidv07", "chrono"]
