[package]
name = "octobot"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
serde = "1.0.188"
lazy_static = "1.4.0"
diesel_migrations = "2.1.0"
tokio = { version = "1.32.0", features = ["full"] }
chrono = { version = "0.4.31", default-features = false }
serde_json = "1.0.107"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
tracing-appender = "0.2.2"
cron = "0.12.0"
graphql_client = { version = "0.13.0", features = ["reqwest"] }
reqwest = "0.11.20"
poise = { git = "https://github.com/serenity-rs/poise", rev = "928d777635c61dbbcd8ed291c772708ead7e43e6", features = ["cache"] }
anyhow = "1.0.75"
async-trait = "0.1.73"
thiserror = "1.0.48"
r2d2 = "0.8.10"

[dependencies.diesel]
version = "2.1.1"
features = ["postgres", "r2d2", "chrono", "uuid"]

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "serde"]

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = [
    "user-hooks",
] }
