# configuration for https://rust-lang.github.io/rustfmt/

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = true
comment_width = 100
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
