name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DISCORD_WEBHOOK: ${{ secrets.FO_DISCORD_WEB_DEVELOPMENT_WEBHOOK }}



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: build
      run: cargo build --verbose
    - name: Run tests
      id: test
      run: cargo test --verbose
    - name: Setup notification
      uses: kceb/pull-request-url-action@v1
      id: pr-url
    - name: Actions Status Discord
      uses: sarisia/actions-status-discord@v1.10.0
      with:
        url: ${{ steps.pr-url.outputs.url }}
      

    
